services:

  nginx:
    image: heartexlabs/label-studio:1.14.0
    container_name: nginx
    restart: unless-stopped
    ports:
        - "8080:8085"
        - "8081:8086"
    depends_on:
      - app
    env_file:
      - env.list
    volumes:
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/certs:/certs:ro
        #- ./deploy/my.conf:/etc/nginx/nginx.conf
    command: nginx

  app:
    stdin_open: true
    tty: true
    image: heartexlabs/label-studio:1.14.0
    container_name: label-studio
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - env.list
    volumes:
      - ./mydata:/label-studio/data:rw
    command: label-studio-uwsgi

  db:
    image: pgautoupgrade/pgautoupgrade:13-alpine
    container_name: postgres
    hostname: db
    restart: unless-stopped
    env_file:
      - env.list
    volumes:
      - ${POSTGRES_DATA_DIR:-./postgres-data}:/var/lib/postgresql/data
      - ./deploy/pgsql/certs:/var/lib/postgresql/certs:ro
